### ISSUE TITLE
AttributeError: can't set attribute when setting up backend

### ISSUE THREAD

**Issue by russellneville** [codeforpdx/dwellingly-app#510]
**Describe the bug**
On Mac based on an exception encountered with an old version of pipenv.  running setup step 6: `pipenv run flask db create` with pipenv version 2018.11.14 resulted in an `AttributeError: can't set attribute exception`.

**To Reproduce**
1. Have an old version of pipenv installed, such as 2018.11.14
2. Attempt to run through the steps in `dwellingbackend/CONTRIBUTING.md`

**Expected behavior**
No exceptions

**Screenshots**
```
Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py:3428: SAWarning: relationship 'StaffTenantLink.tenant' will copy column tenants.id to column staff_tenant_links.tenant_id, which conflicts with relationship(s): 'TenantModel.staff' (copies tenants.id to staff_tenant_links.tenant_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
  util.warn(
/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py:3428: SAWarning: relationship 'StaffTenantLink.staff' will copy column users.id to column staff_tenant_links.staff_id, which conflicts with relationship(s): 'TenantModel.staff' (copies users.id to staff_tenant_links.staff_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
  util.warn(
Traceback (most recent call last):
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/click/core.py", line 955, in main
    rv = self.invoke(ctx)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/click/core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/click/core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/click/core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/click/core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/click/decorators.py", line 18, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/click/core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "/Users/r633114/workspace/hackathon2021/Dwellingly/dwellinglybackend/manage.py", line 22, in create
    db.create_all()
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 560, in get_engine
    options = self.get_options(sa_url, echo)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 575, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/Users/r633114/.envs/dwellinglybackend--dvbsI5j/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 908, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
```

**Desktop (please complete the following information):**
 - OS: macOS Mojave v10.14.6 
 - Browser n/a
 - Version n/a

**Smartphone (please complete the following information):**
 n/a

**Additional context**
The issue was resolved by updating pipenv. Added an additional case to Mac Troublshooting section of CONTRIBUTING.md

**Comment by aedwardg** [comment]
Closed since this is stale.  Feel free to reopen

**Comment by exeptionerror** [comment]
[[Solved] AttributeError: can’t set attribute when connecting to sqlite database with flask-sqlalchemy
](https://exerror.com/attributeerror-cant-set-attribute-when-connecting-to-sqlite-database-with-flask/)
